# -*- coding: utf-8 -*-
"""Hands-on-llm

Automatically generated by Colab.
"""

# !pip install -U langchain langchain-core langchain-community --q
# !wget https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-fp16.gguf

from langchain_community.llms import LlamaCpp

llm = LlamaCpp(
    model_path="./Phi-3-mini-4k-instruct-fp16.gguf",
    n_gpu_layers=-1,
    max_tokens=500,
    n_ctx=2048,
    seed=42,
    verbose=False
)

from langchain_core.prompts import PromptTemplate

template = """<|user|>
{input_prompt}<|end|>
<|assistant|>"""
prompt = PromptTemplate(
    template=template,
    input_variables=["input_prompt"]
)

basic_chain = prompt | llm

basic_chain.invoke(
    {
        "input_prompt": "Hello! What's 1+1?"
    }
)

joke_template = "Create a goofy joke about {input}"
joke_prompt = PromptTemplate(
    template=joke_template,
    input_variables=["input"]
)
joke_chain = joke_prompt | llm
joke_chain.invoke(
    {
        "input": "cats"
    }
)

def generate_title(llm, summary):
    prompt = PromptTemplate(
        template="""<|user|>
Create a title for a story about {summary}. Only return the title.
<|end|>
<|assistant|>""",
        input_variables=["summary"]
    )
    return llm.invoke(prompt.format(summary=summary)).strip()

def generate_character(llm, summary, title):
    prompt = PromptTemplate(
        template="""<|user|>
Describe the main character of a story about {summary} with the title {title}.
Use only two sentences.
<|end|>
<|assistant|>""",
        input_variables=["summary", "title"]
    )
    return llm.invoke(
        prompt.format(summary=summary, title=title)
    ).strip()

def generate_story(llm, summary, title, character):
    prompt = PromptTemplate(
        template="""<|user|>
Create a story about {summary} with the title {title}.
The main character is: {character}.
Only return the story and it cannot be longer than one paragraph.
<|end|>
<|assistant|>""",
        input_variables=["summary", "title", "character"]
    )
    return llm.invoke(
        prompt.format(summary=summary, title=title, character=character)
    ).strip()

def run_story_pipeline(llm, summary):
    title = generate_title(llm, summary)
    character = generate_character(llm, summary, title)
    story = generate_story(llm, summary, title, character)
    return {
        "title": title,
        "character": character,
        "story": story,
    }

run_story_pipeline(llm, "a girl that lost her mother")

